# Generated by Django 3.1.5 on 2021-01-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finchart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fstatement',
            old_name='bs_gross_sales',
            new_name='pl_gross_sales',
        ),
    ]
